[package]
name = "the-labyrinth"
version = "0.0.1"
authors = ["Leandro Lisboa Penz <lpenz@lpenz.org>"]
build = "build.rs"
edition = "2024"

[lib]
doctest = false

[build-dependencies]
rustsourcebundler = "0.14.1"
# rustsourcebundler = { git = "https://github.com/lpenz/rust-sourcebundler", branch = "devel" }

[dependencies]
itertools = "0.14.0"
libc = "0.2.186"
rand = "0.10.1"
regex = "1.12.3"
# time = "0.2.26"

[dev-dependencies]
anyhow = "1"

[dependencies.chrono]
version = "0.4.44"
default-features = false
features = ["clock"]

